version: '3'
services:
  pg:
    image: postgres:10.7
    ports:
      - "5432:5432"
    volumes:
      - "/var/lib/postgres"
    environment:
      - POSTGRES_DB=api
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - pg
